services:
  chroma-db:
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/data
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true


volumes:
  chroma-data: