"""empty message

Revision ID: 4e4296c92e89
Revises: 
Create Date: 2025-03-09 05:44:24.729896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4296c92e89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_chat_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_chat_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('history_file_name', sa.VARCHAR(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('prep_studio', sa.BOOLEAN(), nullable=True),
    sa.Column('bot_configuration_result', sa.VARCHAR(length=3000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
